name: publish-release

on:
  push:
    tags: ['*']
  workflow_dispatch:

jobs:
  release:
    name: 'publish release'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v6
      - name: Convert Markdown to PDF
        uses: your-username/markdown-to-pdf-action@v2
        with:
          markdown_dir: './docs'
          markdown_file: 'README.md'
          output_dir: './docs'
      - name: Draft release
        uses: softprops/action-gh-release@v3
        with:
          body: ${{ github.event.pull_request.title }}
          draft: true
          fail_on_unmatched_files: true
          files: docs/README.pdf
          name: Release ${{ github.ref }}
